services:
  - type: web
    name: obsolescence-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_USERNAME
        sync: false
      - key: API_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true
